"""add_file_progress_columns

Revision ID: 0bb215e40ee2
Revises: 20260424_0005
Create Date: 2026-06-01 19:44:42.082786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0bb215e40ee2'
down_revision: Union[str, None] = '20260424_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_response_cache_id'), 'ai_response_cache', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_contents_id'), 'extracted_contents', ['id'], unique=False)
    op.add_column('files', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.execute("UPDATE files SET progress_percent = 0")
    op.alter_column('files', 'progress_percent', nullable=False)
    op.add_column('files', sa.Column('detailed_steps', sa.Text(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('files', 'detailed_steps')
    op.drop_column('files', 'progress_percent')
    op.drop_index(op.f('ix_extracted_contents_id'), table_name='extracted_contents')
    op.drop_index(op.f('ix_ai_response_cache_id'), table_name='ai_response_cache')
    # ### end Alembic commands ###
