"""add_conversational_memory_columns

Revision ID: 7d3682e5957e
Revises: 20260609_0007
Create Date: 2026-06-12 11:32:16.919042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7d3682e5957e'
down_revision: Union[str, None] = '20260609_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_response_cache', sa.Column('is_summarized', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notes', sa.Column('conversation_summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_source_summaries_user_id'), 'source_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_summaries_user_id'), table_name='source_summaries')
    op.drop_column('notes', 'conversation_summary')
    op.drop_column('ai_response_cache', 'is_summarized')
    # ### end Alembic commands ###
